
// Helper to normalize strings for search (remove diacritics, lowercase)
const normalize = (str) => {
    if (!str) return "";
    return str.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase();
};

const citiesData = [
    // --- POLAND (PL) ---
    { name: "Warszawa", country: "PL", names: ["Warszawa", "Warsaw", "Варшава", "Варшава"] },
    { name: "Kraków", country: "PL", names: ["Kraków", "Cracow", "Краков", "Краків"] },
    { name: "Łódź", country: "PL", names: ["Łódź", "Lodz", "Лодзь", "Лодзь"] },
    { name: "Wrocław", country: "PL", names: ["Wrocław", "Wroclaw", "Вроцлав", "Вроцлав"] },
    { name: "Poznań", country: "PL", names: ["Poznań", "Poznan", "Познань", "Познань"] },
    { name: "Gdańsk", country: "PL", names: ["Gdańsk", "Gdansk", "Гданьск", "Гданськ"] },
    { name: "Szczecin", country: "PL", names: ["Szczecin", "Щецин", "Щецин"] },
    { name: "Bydgoszcz", country: "PL", names: ["Bydgoszcz", "Быдгощ", "Бидгощ"] },
    { name: "Lublin", country: "PL", names: ["Lublin", "Люблин", "Люблін"] },
    { name: "Białystok", country: "PL", names: ["Białystok", "Bialystok", "Белосток", "Білосток"] },
    { name: "Katowice", country: "PL", names: ["Katowice", "Катовице", "Катовіце"] },
    { name: "Gdynia", country: "PL", names: ["Gdynia", "Гдыня", "Гдиня"] },
    { name: "Częstochowa", country: "PL", names: ["Częstochowa", "Czestochowa", "Ченстохова", "Ченстохова"] },
    { name: "Radom", country: "PL", names: ["Radom", "Радом", "Радом"] },
    { name: "Rzeszów", country: "PL", names: ["Rzeszów", "Rzeszow", "Жешув", "Ряшів"] },
    { name: "Toruń", country: "PL", names: ["Toruń", "Torun", "Торунь", "Торунь"] },
    { name: "Kielce", country: "PL", names: ["Kielce", "Кельце", "Кельці"] },
    { name: "Gliwice", country: "PL", names: ["Gliwice", "Гливице", "Глівіце"] },
    { name: "Olsztyn", country: "PL", names: ["Olsztyn", "Ольштын", "Ольштин"] },
    { name: "Zabrze", country: "PL", names: ["Zabrze", "Забже", "Забже"] },
    { name: "Bielsko-Biała", country: "PL", names: ["Bielsko-Biała", "Bielsko-Biala", "Бельско-Бяла", "Бєльсько-Бяла"] },
    { name: "Bytom", country: "PL", names: ["Bytom", "Бытом", "Битом"] },
    { name: "Zielona Góra", country: "PL", names: ["Zielona Góra", "Zielona Gora", "Зелёна-Гура", "Зелена Гура"] },
    { name: "Rybnik", country: "PL", names: ["Rybnik", "Рыбник", "Рибник"] },
    { name: "Ruda Śląska", country: "PL", names: ["Ruda Śląska", "Ruda Slaska", "Руда-Слёнска", "Руда-Шльонська"] },
    { name: "Opole", country: "PL", names: ["Opole", "Ополе", "Ополе"] },
    { name: "Tychy", country: "PL", names: ["Tychy", "Тыхы", "Тихи"] },
    { name: "Gorzów Wielkopolski", country: "PL", names: ["Gorzów Wielkopolski", "Gorzow Wielkopolski", "Гожув-Велькопольски", "Гожув-Велькопольський"] },
    { name: "Dąbrowa Górnicza", country: "PL", names: ["Dąbrowa Górnicza", "Dabrowa Gornicza", "Домброва-Гурнича", "Домброва-Гурнича"] },
    { name: "Płock", country: "PL", names: ["Płock", "Plock", "Плоцк", "Плоцьк"] },
    { name: "Elbląg", country: "PL", names: ["Elbląg", "Elblag", "Эльблонг", "Ельблонг"] },
    { name: "Wałbrzych", country: "PL", names: ["Wałbrzych", "Walbrzych", "Валбжих", "Валбжих"] },
    { name: "Włocławek", country: "PL", names: ["Włocławek", "Wloclawek", "Влоцлавек", "Влоцлавек"] },
    { name: "Tarnów", country: "PL", names: ["Tarnów", "Tarnow", "Тарнув", "Тарнів"] },
    { name: "Chorzów", country: "PL", names: ["Chorzów", "Chorzow", "Хожув", "Хожув"] },
    { name: "Koszalin", country: "PL", names: ["Koszalin", "Кошалин", "Кошалін"] },
    { name: "Kalisz", country: "PL", names: ["Kalisz", "Калиш", "Каліш"] },
    { name: "Legnica", country: "PL", names: ["Legnica", "Легница", "Легниця"] },
    { name: "Grudziądz", country: "PL", names: ["Grudziądz", "Grudziadz", "Грудзёндз", "Грудзьондз"] },
    { name: "Jaworzno", country: "PL", names: ["Jaworzno", "Явожно", "Явожно"] },
    { name: "Słupsk", country: "PL", names: ["Słupsk", "Slupsk", "Слупск", "Слупськ"] },
    { name: "Jastrzębie-Zdrój", country: "PL", names: ["Jastrzębie-Zdrój", "Jastrzebie-Zdroj", "Ястшембе-Здруй", "Ястшембе-Здруй"] },
    { name: "Nowy Sącz", country: "PL", names: ["Nowy Sącz", "Nowy Sacz", "Новы-Сонч", "Новий Сонч"] },
    { name: "Jelenia Góra", country: "PL", names: ["Jelenia Góra", "Jelenia Gora", "Еленя-Гура", "Єленя-Гура"] },
    { name: "Siedlce", country: "PL", names: ["Siedlce", "Седльце", "Седльце"] },
    { name: "Mysłowice", country: "PL", names: ["Mysłowice", "Myslowice", "Мысловице", "Мисловіце"] },
    { name: "Konin", country: "PL", names: ["Konin", "Конин", "Конін"] },
    { name: "Piła", country: "PL", names: ["Piła", "Pila", "Пила", "Піла"] },
    { name: "Piotrków Trybunalski", country: "PL", names: ["Piotrków Trybunalski", "Piotrkow Trybunalski", "Пётркув-Трыбунальски", "Пйотркув-Трибунальський"] },
    { name: "Inowrocław", country: "PL", names: ["Inowrocław", "Inowroclaw", "Иновроцлав", "Іновроцлав"] },
    { name: "Lubin", country: "PL", names: ["Lubin", "Любин", "Любін"] },
    { name: "Ostrów Wielkopolski", country: "PL", names: ["Ostrów Wielkopolski", "Ostrow Wielkopolski", "Острув-Велькопольски", "Острув-Велькопольський"] },
    { name: "Suwałki", country: "PL", names: ["Suwałki", "Suwalki", "Сувалки", "Сувалки"] },
    { name: "Stargard", country: "PL", names: ["Stargard", "Старгард", "Старгард"] },
    { name: "Gniezno", country: "PL", names: ["Gniezno", "Гнезно", "Гнєзно"] },
    { name: "Ostrowiec Świętokrzyski", country: "PL", names: ["Ostrowiec Świętokrzyski", "Ostrowiec Swietokrzyski", "Островец-Свентокшиски", "Островець-Свентокшиський"] },
    { name: "Siemianowice Śląskie", country: "PL", names: ["Siemianowice Śląskie", "Siemianowice Slaskie", "Семяновице-Слёнске", "Семяновіце-Шльонське"] },
    { name: "Głogów", country: "PL", names: ["Głogów", "Glogow", "Глогув", "Глогув"] },
    { name: "Pabianice", country: "PL", names: ["Pabianice", "Пабьянице", "Паб'яніце"] },
    { name: "Leszno", country: "PL", names: ["Leszno", "Лешно", "Лешно"] },
    { name: "Żory", country: "PL", names: ["Żory", "Zory", "Жоры", "Жори"] },
    { name: "Zamość", country: "PL", names: ["Zamość", "Zamosc", "Замосць", "Замостя"] },
    { name: "Pruszków", country: "PL", names: ["Pruszków", "Pruszkow", "Прушков", "Прушкув"] },
    { name: "Łomża", country: "PL", names: ["Łomża", "Lomza", "Ломжа", "Ломжа"] },
    { name: "Ełk", country: "PL", names: ["Ełk", "Elk", "Элк", "Елк"] },
    { name: "Tarnowskie Góry", country: "PL", names: ["Tarnowskie Góry", "Tarnowskie Gory", "Тарновске-Гуры", "Тарновські Гури"] },
    { name: "Tomaszów Mazowiecki", country: "PL", names: ["Tomaszów Mazowiecki", "Tomaszow Mazowiecki", "Томашув-Мазовецки", "Томашув-Мазовецький"] },
    { name: "Chełm", country: "PL", names: ["Chełm", "Chelm", "Хелм", "Холм"] },
    { name: "Mielec", country: "PL", names: ["Mielec", "Мелец", "Мелець"] },
    { name: "Kędzierzyn-Koźle", country: "PL", names: ["Kędzierzyn-Koźle", "Kedzierzyn-Kozle", "Кендзежин-Козле", "Кендзежин-Козле"] },
    { name: "Przemyśl", country: "PL", names: ["Przemyśl", "Przemysl", "Пшемысль", "Перемишль"] },
    { name: "Stalowa Wola", country: "PL", names: ["Stalowa Wola", "Сталёва-Воля", "Стальова Воля"] },
    { name: "Tczew", country: "PL", names: ["Tczew", "Тчев", "Тчев"] },
    { name: "Biała Podlaska", country: "PL", names: ["Biała Podlaska", "Biala Podlaska", "Бяла-Подляска", "Бяла-Подляська"] },
    { name: "Bełchatów", country: "PL", names: ["Bełchatów", "Belchatow", "Белхатув", "Белхатув"] },
    { name: "Świdnica", country: "PL", names: ["Świdnica", "Swidnica", "Свидница", "Свідниця"] },
    { name: "Będzin", country: "PL", names: ["Będzin", "Bedzin", "Бендзин", "Бендзин"] },
    { name: "Zgierz", country: "PL", names: ["Zgierz", "Згеж", "Згеж"] },
    { name: "Piekary Śląskie", country: "PL", names: ["Piekary Śląskie", "Piekary Slaskie", "Пекары-Слёнске", "Пекари-Шльонські"] },
    { name: "Racibórz", country: "PL", names: ["Racibórz", "Raciborz", "Рацибуж", "Рацибуж"] },
    { name: "Legionowo", country: "PL", names: ["Legionowo", "Легионово", "Легіоново"] },
    { name: "Ostrołęka", country: "PL", names: ["Ostrołęka", "Ostroleka", "Остроленка", "Остроленка"] },
    { name: "Świętochłowice", country: "PL", names: ["Świętochłowice", "Swietochlowice", "Свентохловице", "Свентохловиці"] },
    { name: "Wejherowo", country: "PL", names: ["Wejherowo", "Вейхерово", "Вейхерово"] },
    { name: "Zawiercie", country: "PL", names: ["Zawiercie", "Заверце", "Заверці"] },
    { name: "Skierniewice", country: "PL", names: ["Skierniewice", "Скерневице", "Скерневиці"] },
    { name: "Starachowice", country: "PL", names: ["Starachowice", "Стараховице", "Стараховіце"] },
    { name: "Wodzisław Śląski", country: "PL", names: ["Wodzisław Śląski", "Wodzislaw Slaski", "Водзислав-Слёнски", "Водзіслав-Шльонський"] },
    { name: "Starogard Gdański", country: "PL", names: ["Starogard Gdański", "Starogard Gdanski", "Старогард-Гданьски", "Старогард-Гданський"] },
    { name: "Puławy", country: "PL", names: ["Puławy", "Pulawy", "Пулавы", "Пулави"] },
    { name: "Tarnobrzeg", country: "PL", names: ["Tarnobrzeg", "Тарнобжег", "Тарнобжег"] },
    { name: "Kołobrzeg", country: "PL", names: ["Kołobrzeg", "Kolobrzeg", "Колобжег", "Колобжег"] },
    { name: "Krosno", country: "PL", names: ["Krosno", "Кросно", "Кросно"] },
    { name: "Radomsko", country: "PL", names: ["Radomsko", "Радомско", "Радомсько"] },
    { name: "Otwock", country: "PL", names: ["Otwock", "Отвоцк", "Отвоцьк"] },
    { name: "Skarżysko-Kamienna", country: "PL", names: ["Skarżysko-Kamienna", "Skarzysko-Kamienna", "Скаржиско-Каменна", "Скаржисько-Каменна"] },
    { name: "Ciechanów", country: "PL", names: ["Ciechanów", "Ciechanow", "Цеханув", "Цеханув"] },
    { name: "Kutno", country: "PL", names: ["Kutno", "Кутно", "Кутно"] },
    { name: "Sieradz", country: "PL", names: ["Sieradz", "Серадз", "Серадз"] },
    { name: "Zduńska Wola", country: "PL", names: ["Zduńska Wola", "Zdunska Wola", "Здуньска-Воля", "Здунська-Воля"] },
    { name: "Świnoujście", country: "PL", names: ["Świnoujście", "Swinoujscie", "Свиноуйсьце", "Свіноуйсьце"] },
    { name: "Żyrardów", country: "PL", names: ["Żyrardów", "Zyrardow", "Жирардув", "Жирардув"] },
    { name: "Bolesławiec", country: "PL", names: ["Bolesławiec", "Boleslawiec", "Болеславец", "Болеславець"] },
    { name: "Nowa Sól", country: "PL", names: ["Nowa Sól", "Nowa Sol", "Нова-Суль", "Нова Суль"] },
    { name: "Knurów", country: "PL", names: ["Knurów", "Knurow", "Кнурув", "Кнурув"] },
    { name: "Oświęcim", country: "PL", names: ["Oświęcim", "Oswiecim", "Освенцим", "Освенцим"] },
    { name: "Sopot", country: "PL", names: ["Sopot", "Сопот", "Сопот"] },
    { name: "Sanok", country: "PL", names: ["Sanok", "Санок", "Сянок"] },
    { name: "Rumia", country: "PL", names: ["Rumia", "Румя", "Румя"] },
    { name: "Jarosław", country: "PL", names: ["Jarosław", "Jaroslaw", "Ярослав", "Ярослав"] },
    { name: "Żywiec", country: "PL", names: ["Żywiec", "Zywiec", "Живец", "Живець"] },
    { name: "Szczecinek", country: "PL", names: ["Szczecinek", "Щецинек", "Щецинек"] },
    { name: "Chojnice", country: "PL", names: ["Chojnice", "Хойнице", "Хойніце"] },
    { name: "Malbork", country: "PL", names: ["Malbork", "Мальборк", "Мальборк"] },
    { name: "Kwidzyn", country: "PL", names: ["Kwidzyn", "Квидзын", "Квідзин"] },
    { name: "Kraśnik", country: "PL", names: ["Kraśnik", "Krasnik", "Красник", "Красник"] },
    { name: "Mława", country: "PL", names: ["Mława", "Mlawa", "Млава", "Млава"] },
    { name: "Września", country: "PL", names: ["Września", "Wrzesnia", "Вжесня", "Вжесня"] },
    { name: "Łuków", country: "PL", names: ["Łuków", "Lukow", "Лукув", "Луків"] },
    { name: "Wołomin", country: "PL", names: ["Wołomin", "Wolomin", "Воломин", "Воломін"] },
    { name: "Czeladź", country: "PL", names: ["Czeladź", "Czeladz", "Челядзь", "Челядзь"] },
    { name: "Lębork", country: "PL", names: ["Lębork", "Lebork", "Лемборк", "Лемборк"] },
    { name: "Cieszyn", country: "PL", names: ["Cieszyn", "Цешин", "Цешин"] },
    { name: "Piaseczno", country: "PL", names: ["Piaseczno", "Пясечно", "Пясечно"] },
    { name: "Zgorzelec", country: "PL", names: ["Zgorzelec", "Згожелец", "Згожелець"] },
    { name: "Zakopane", country: "PL", names: ["Zakopane", "Закопане", "Закопане"] },

    // --- BELARUS (BY) ---
    { name: "Minsk", country: "BY", names: ["Minsk", "Mińsk", "Минск", "Мінськ"] },
    { name: "Gomel", country: "BY", names: ["Gomel", "Homel", "Гомель", "Гомель"] },
    { name: "Mogilev", country: "BY", names: ["Mogilev", "Mahilyow", "Могилев", "Могильов"] },
    { name: "Vitebsk", country: "BY", names: ["Vitebsk", "Vitsyebsk", "Витебск", "Вітебськ"] },
    { name: "Grodno", country: "BY", names: ["Grodno", "Hrodna", "Гродно", "Гродно"] },
    { name: "Brest", country: "BY", names: ["Brest", "Брест", "Брест"] },
    { name: "Bobruisk", country: "BY", names: ["Bobruisk", "Babruysk", "Бобруйск", "Бобруйськ"] },
    { name: "Baranovichi", country: "BY", names: ["Baranovichi", "Baranavichy", "Барановичи", "Барановичі"] },
    { name: "Borisov", country: "BY", names: ["Borisov", "Barysaw", "Борисов", "Борисов"] },
    { name: "Pinsk", country: "BY", names: ["Pinsk", "Пинск", "Пінськ"] },
    { name: "Orsha", country: "BY", names: ["Orsha", "Arsha", "Орша", "Орша"] },
    { name: "Mozyr", country: "BY", names: ["Mozyr", "Mazyr", "Мозырь", "Мозир"] },
    { name: "Soligorsk", country: "BY", names: ["Soligorsk", "Salihorsk", "Солигорск", "Солігорськ"] },
    { name: "Lida", country: "BY", names: ["Lida", "Лида", "Ліда"] },
    { name: "Novopolotsk", country: "BY", names: ["Novopolotsk", "Navapolatsk", "Новополоцк", "Новополоцьк"] },
    { name: "Molodechno", country: "BY", names: ["Molodechno", "Maladzyechna", "Молодечно", "Молодечно"] },
    { name: "Polotsk", country: "BY", names: ["Polotsk", "Polatsk", "Полоцк", "Полоцьк"] },
    { name: "Zhlobin", country: "BY", names: ["Zhlobin", "Жлобин", "Жлобин"] },
    { name: "Svetlogorsk", country: "BY", names: ["Svetlogorsk", "Svietlahorsk", "Светлогорск", "Світлогорськ"] },
    { name: "Rechitsa", country: "BY", names: ["Rechitsa", "Rechytsa", "Речица", "Річиця"] },
    { name: "Slutsk", country: "BY", names: ["Slutsk", "Слуцк", "Слуцьк"] },
    { name: "Zhodino", country: "BY", names: ["Zhodino", "Zhodzina", "Жодино", "Жодіно"] },
    { name: "Slonim", country: "BY", names: ["Slonim", "Слоним", "Слонім"] },
    { name: "Kobrin", country: "BY", names: ["Kobrin", "Kobryn", "Кобрин", "Кобринь"] },
    { name: "Volkovysk", country: "BY", names: ["Volkovysk", "Vawkavysk", "Волковыск", "Вовковиськ"] },
    { name: "Kalinkovichi", country: "BY", names: ["Kalinkovichi", "Kalinkavichy", "Калинковичи", "Калинковичі"] },
    { name: "Smorgon", country: "BY", names: ["Smorgon", "Smarhon", "Сморгонь", "Сморгонь"] },
    { name: "Rogachev", country: "BY", names: ["Rogachev", "Rahachow", "Рогачев", "Рогачов"] },
    { name: "Osipovichi", country: "BY", names: ["Osipovichi", "Asipovichy", "Осиповичи", "Осиповичі"] },
    { name: "Gorki", country: "BY", names: ["Gorki", "Horki", "Горки", "Гірки"] },
    { name: "Novogrudok", country: "BY", names: ["Novogrudok", "Navahrudak", "Новогрудок", "Новогрудок"] },
    { name: "Vilejka", country: "BY", names: ["Vilejka", "Vileyka", "Вилейка", "Вілейка"] },
    { name: "Berezha", country: "BY", names: ["Berezha", "Byaroza", "Береза", "Береза"] },
    { name: "Krichev", country: "BY", names: ["Krichev", "Krychaw", "Кричев", "Кричев"] },
    { name: "Dzerzhinsk", country: "BY", names: ["Dzerzhinsk", "Dzyarzhynsk", "Дзержинск", "Дзержинськ"] },
    { name: "Ivatsevichi", country: "BY", names: ["Ivatsevichi", "Ivatsevichy", "Ивацевичи", "Івацевичі"] },
    { name: "Luninets", country: "BY", names: ["Luninets", "Лунинец", "Лунинець"] },
    { name: "Maryina Gorka", country: "BY", names: ["Maryina Gorka", "Maryina Horka", "Марьина Горка", "Мар'їна Гірка"] },
    { name: "Postavy", country: "BY", names: ["Postavy", "Pastavy", "Поставы", "Постави"] },
    { name: "Pruzhany", country: "BY", names: ["Pruzhany", "Пружаны", "Пружани"] },
    { name: "Glubokoe", country: "BY", names: ["Glubokoe", "Hlybokaye", "Глубокое", "Глибоке"] },
    { name: "Dobrush", country: "BY", names: ["Dobrush", "Добруш", "Добруш"] },
    { name: "Lepel", country: "BY", names: ["Lepel", "Лепель", "Лепель"] },
    { name: "Bykhov", country: "BY", names: ["Bykhov", "Bykhaw", "Быхов", "Бихов"] },
    { name: "Ivanovo", country: "BY", names: ["Ivanovo", "Ivanava", "Иваново", "Іванове"] },
    { name: "Klimovichi", country: "BY", names: ["Klimovichi", "Klimavichy", "Климовичи", "Климовичі"] },
    { name: "Shklov", country: "BY", names: ["Shklov", "Shklow", "Шклов", "Шклов"] },
    { name: "Stolbtsy", country: "BY", names: ["Stolbtsy", "Stowbtsy", "Столбцы", "Стовбці"] },
    { name: "Kostyukovichi", country: "BY", names: ["Kostyukovichi", "Kastsyukovichy", "Костюковичи", "Костюковичі"] },
    { name: "Zhitkovichi", country: "BY", names: ["Zhitkovichi", "Zhytkavichy", "Житковичи", "Житковичі"] },
    { name: "Mosty", country: "BY", names: ["Mosty", "Masty", "Мосты", "Мости"] },
    { name: "Oshmyany", country: "BY", names: ["Oshmyany", "Ashmyany", "Ошмяны", "Ошмяни"] },
    { name: "Smolevichi", country: "BY", names: ["Smolevichi", "Smalyavichy", "Смолевичи", "Смолевичі"] },
    { name: "Shchuchin", country: "BY", names: ["Shchuchin", "Shchuchyn", "Щучин", "Щучин"] },
    { name: "Nesvizh", country: "BY", names: ["Nesvizh", "Niasvizh", "Несвиж", "Несвіж"] },

    // --- UKRAINE (UA) ---
    { name: "Kyiv", country: "UA", names: ["Kyiv", "Kiev", "Kijów", "Киев", "Київ"] },
    { name: "Kharkiv", country: "UA", names: ["Kharkiv", "Kharkov", "Charków", "Харьков", "Харків"] },
    { name: "Odesa", country: "UA", names: ["Odesa", "Odessa", "Одесса", "Одеса"] },
    { name: "Dnipro", country: "UA", names: ["Dnipro", "Dnepr", "Dniepr", "Днепр", "Дніпро"] },
    { name: "Donetsk", country: "UA", names: ["Donetsk", "Донецк", "Донецьк"] },
    { name: "Zaporizhzhia", country: "UA", names: ["Zaporizhzhia", "Zaporozhye", "Запорожье", "Запоріжжя"] },
    { name: "Lviv", country: "UA", names: ["Lviv", "Lvov", "Lwów", "Львов", "Львів"] },
    { name: "Kryvyi Rih", country: "UA", names: ["Kryvyi Rih", "Krivoy Rog", "Кривой Рог", "Кривий Ріг"] },
    { name: "Mykolaiv", country: "UA", names: ["Mykolaiv", "Nikolaev", "Николаев", "Миколаїв"] },
    { name: "Mariupol", country: "UA", names: ["Mariupol", "Мариуполь", "Маріуполь"] },
    { name: "Luhansk", country: "UA", names: ["Luhansk", "Lugansk", "Луганск", "Луганськ"] },
    { name: "Vinnytsia", country: "UA", names: ["Vinnytsia", "Vinnitsa", "Винница", "Вінниця"] },
    { name: "Makiivka", country: "UA", names: ["Makiivka", "Makeevka", "Макеевка", "Макіївка"] },
    { name: "Sevastopol", country: "UA", names: ["Sevastopol", "Севастополь", "Севастополь"] },
    { name: "Simferopol", country: "UA", names: ["Simferopol", "Симферополь", "Сімферополь"] },
    { name: "Kherson", country: "UA", names: ["Kherson", "Херсон", "Херсон"] },
    { name: "Poltava", country: "UA", names: ["Poltava", "Полтава", "Полтава"] },
    { name: "Chernihiv", country: "UA", names: ["Chernihiv", "Chernigov", "Чернигов", "Чернігів"] },
    { name: "Cherkasy", country: "UA", names: ["Cherkasy", "Cherkassy", "Черкассы", "Черкаси"] },
    { name: "Khmelnytskyi", country: "UA", names: ["Khmelnytskyi", "Khmelnitsky", "Хмельницкий", "Хмельницький"] },
    { name: "Zhytomyr", country: "UA", names: ["Zhytomyr", "Zhitomir", "Житомир", "Житомир"] },
    { name: "Chernivtsi", country: "UA", names: ["Chernivtsi", "Chernovtsy", "Черновцы", "Чернівці"] },
    { name: "Sumy", country: "UA", names: ["Sumy", "Сумы", "Суми"] },
    { name: "Rivne", country: "UA", names: ["Rivne", "Rovno", "Ровно", "Рівне"] },
    { name: "Ivano-Frankivsk", country: "UA", names: ["Ivano-Frankivsk", "Ивано-Франковск", "Івано-Франківськ"] },
    { name: "Kamianske", country: "UA", names: ["Kamianske", "Dneprodzerzhinsk", "Каменское", "Кам'янське"] },
    { name: "Kropyvnytskyi", country: "UA", names: ["Kropyvnytskyi", "Kirovograd", "Кропивницкий", "Кропивницький"] },
    { name: "Ternopil", country: "UA", names: ["Ternopil", "Ternopol", "Тернополь", "Тернопіль"] },
    { name: "Kremenchuk", country: "UA", names: ["Kremenchuk", "Kremenchug", "Кременчуг", "Кременчук"] },
    { name: "Lutsk", country: "UA", names: ["Lutsk", "Луцк", "Луцьк"] },
    { name: "Bila Tserkva", country: "UA", names: ["Bila Tserkva", "Belaya Tserkov", "Белая Церковь", "Біла Церква"] },
    { name: "Uzhhorod", country: "UA", names: ["Uzhhorod", "Uzhgorod", "Ужгород", "Ужгород"] },
    { name: "Kramatorsk", country: "UA", names: ["Kramatorsk", "Краматорск", "Краматорськ"] },
    { name: "Melitopol", country: "UA", names: ["Melitopol", "Мелитополь", "Мелітополь"] },
    { name: "Kerch", country: "UA", names: ["Kerch", "Керчь", "Керч"] },
    { name: "Nikopol", country: "UA", names: ["Nikopol", "Никополь", "Нікополь"] },
    { name: "Sloviansk", country: "UA", names: ["Sloviansk", "Slavyansk", "Славянск", "Слов'янськ"] },
    { name: "Berdiansk", country: "UA", names: ["Berdiansk", "Berdyansk", "Бердянск", "Бердянськ"] },
    { name: "Alchevsk", country: "UA", names: ["Alchevsk", "Алчевск", "Алчевськ"] },
    { name: "Pavlohrad", country: "UA", names: ["Pavlohrad", "Pavlograd", "Павлоград", "Павлоград"] },
    { name: "Sievierodonetsk", country: "UA", names: ["Sievierodonetsk", "Severodonetsk", "Северодонецк", "Сєвєродонецьк"] },
    { name: "Yevpatoria", country: "UA", names: ["Yevpatoria", "Евпатория", "Євпаторія"] },
    { name: "Lysychansk", country: "UA", names: ["Lysychansk", "Lisichansk", "Лисичанск", "Лисичанськ"] },
    { name: "Kamianets-Podilskyi", country: "UA", names: ["Kamianets-Podilskyi", "Kamenets-Podolsky", "Каменец-Подольский", "Кам'янець-Подільський"] },
    { name: "Brovary", country: "UA", names: ["Brovary", "Бровары", "Бровари"] },
    { name: "Konotop", country: "UA", names: ["Konotop", "Конотоп", "Конотоп"] },
    { name: "Uman", country: "UA", names: ["Uman", "Умань", "Умань"] },
    { name: "Mukachevo", country: "UA", names: ["Mukachevo", "Mukacheve", "Мукачево", "Мукачево"] },
    { name: "Oleksandriia", country: "UA", names: ["Oleksandriia", "Alexandria", "Александрия", "Олександрія"] },
    { name: "Khrustalnyi", country: "UA", names: ["Khrustalnyi", "Krasny Luch", "Красный Луч", "Хрустальний"] },
    { name: "Yenakiieve", country: "UA", names: ["Yenakiieve", "Yenakievo", "Енакиево", "Єнакієве"] },
    { name: "Drohobych", country: "UA", names: ["Drohobych", "Drogobych", "Дрогобыч", "Дрогобич"] },
    { name: "Berdychiv", country: "UA", names: ["Berdychiv", "Berdichev", "Бердичев", "Бердичів"] },
    { name: "Shostka", country: "UA", names: ["Shostka", "Шостка", "Шостка"] },
    { name: "Bakhmut", country: "UA", names: ["Bakhmut", "Artemovsk", "Бахмут", "Бахмут"] },
    { name: "Izmail", country: "UA", names: ["Izmail", "Измаил", "Ізмаїл"] },
    { name: "Novomoskovsk", country: "UA", names: ["Novomoskovsk", "Новомосковск", "Новомосковськ"] },
    { name: "Kostiantynivka", country: "UA", names: ["Kostiantynivka", "Konstantinovka", "Константиновка", "Костянтинівка"] },
    { name: "Kovel", country: "UA", names: ["Kovel", "Ковель", "Ковель"] },
    { name: "Feodosia", country: "UA", names: ["Feodosia", "Феодосия", "Феодосія"] },
    { name: "Nizhyn", country: "UA", names: ["Nizhyn", "Nezhin", "Нежин", "Ніжин"] },
    { name: "Smila", country: "UA", names: ["Smila", "Smela", "Смела", "Сміла"] },
    { name: "Kalush", country: "UA", names: ["Kalush", "Калуш", "Калуш"] },
    { name: "Chervonohrad", country: "UA", names: ["Chervonohrad", "Chervonograd", "Червоноград", "Червоноград"] },
    { name: "Boryspil", country: "UA", names: ["Boryspil", "Borispol", "Борисполь", "Бориспіль"] },
    { name: "Pervomaisk", country: "UA", names: ["Pervomaisk", "Первомайск", "Первомайськ"] },
    { name: "Irpin", country: "UA", names: ["Irpin", "Ирпень", "Ірпінь"] },
    { name: "Korosten", country: "UA", names: ["Korosten", "Коростень", "Коростень"] },
    { name: "Pokrovsk", country: "UA", names: ["Pokrovsk", "Krasnoarmeysk", "Покровск", "Покровськ"] },
    { name: "Kolomyia", country: "UA", names: ["Kolomyia", "Kolomyya", "Коломыя", "Коломия"] },
    { name: "Stryi", country: "UA", names: ["Stryi", "Stryy", "Стрый", "Стрий"] },
    { name: "Chornomorsk", country: "UA", names: ["Chornomorsk", "Illichivsk", "Черноморск", "Чорноморськ"] },
    { name: "Khartsyzk", country: "UA", names: ["Khartsyzk", "Харцызск", "Харцизьк"] },
    { name: "Rubizhne", country: "UA", names: ["Rubizhne", "Rubezhnoe", "Рубежное", "Рубіжне"] },
    { name: "Novohrad-Volynskyi", country: "UA", names: ["Novohrad-Volynskyi", "Novograd-Volynsky", "Новоград-Волынский", "Новоград-Волинський"] },
    { name: "Druzhkivka", country: "UA", names: ["Druzhkivka", "Druzhkovka", "Дружковка", "Дружківка"] },
    { name: "Lozova", country: "UA", names: ["Lozova", "Lozovaya", "Лозовая", "Лозова"] },
    { name: "Chystiakove", country: "UA", names: ["Chystiakove", "Torez", "Чистяково", "Чистякове"] },
    { name: "Enerhodar", country: "UA", names: ["Enerhodar", "Energodar", "Энергодар", "Енергодар"] },
    { name: "Pryluky", country: "UA", names: ["Pryluky", "Priluki", "Прилуки", "Прилуки"] },
    { name: "Antratsyt", country: "UA", names: ["Antratsyt", "Antratsit", "Антрацит", "Антрацит"] },
    { name: "Novovolynsk", country: "UA", names: ["Novovolynsk", "Нововолынск", "Нововолинськ"] },
    { name: "Horishni Plavni", country: "UA", names: ["Horishni Plavni", "Komsomolsk", "Горишние Плавни", "Горішні Плавні"] },
    { name: "Shakhtarsk", country: "UA", names: ["Shakhtarsk", "Shakhtersk", "Шахтерск", "Шахтарськ"] },
    { name: "Bilhorod-Dnistrovskyi", country: "UA", names: ["Bilhorod-Dnistrovskyi", "Belgorod-Dnestrovsky", "Белгород-Днестровский", "Білгород-Дністровський"] },
    { name: "Okhtyrka", country: "UA", names: ["Okhtyrka", "Akhtyrka", "Ахтырка", "Охтирка"] },
    { name: "Myrnohrad", country: "UA", names: ["Myrnohrad", "Dimitrov", "Мирноград", "Мирноград"] },
    { name: "Snizhne", country: "UA", names: ["Snizhne", "Snezhnoe", "Снежное", "Сніжне"] },
    { name: "Izium", country: "UA", names: ["Izium", "Izyum", "Изюм", "Ізюм"] },
    { name: "Marhanets", country: "UA", names: ["Marhanets", "Marganets", "Марганец", "Марганець"] },
    { name: "Rovenky", country: "UA", names: ["Rovenky", "Rovenki", "Ровеньки", "Ровеньки"] },
    { name: "Nova Kakhovka", country: "UA", names: ["Nova Kakhovka", "Новая Каховка", "Нова Каховка"] },
    { name: "Brianka", country: "UA", names: ["Brianka", "Bryanka", "Брянка", "Брянка"] },
    { name: "Fastiv", country: "UA", names: ["Fastiv", "Fastov", "Фастов", "Фастів"] },
    { name: "Lubny", country: "UA", names: ["Lubny", "Лубны", "Лубни"] },
    { name: "Svitlovodsk", country: "UA", names: ["Svitlovodsk", "Svetlovodsk", "Светловодск", "Світловодськ"] },
    { name: "Zhovti Vody", country: "UA", names: ["Zhovti Vody", "Zheltye Vody", "Желтые Воды", "Жовті Води"] },
    { name: "Krasnodon", country: "UA", names: ["Krasnodon", "Sorokyne", "Краснодон", "Сорокине"] },
    { name: "Vyshneve", country: "UA", names: ["Vyshneve", "Vishnevoe", "Вишневое", "Вишневе"] },
    { name: "Varash", country: "UA", names: ["Varash", "Kuznetsovsk", "Вараш", "Вараш"] },
    { name: "Shepetivka", country: "UA", names: ["Shepetivka", "Shepetovka", "Шепетовка", "Шепетівка"] },
    { name: "Podilsk", country: "UA", names: ["Podilsk", "Kotovsk", "Подольск", "Подільськ"] },
    { name: "Yuzhnoukrainsk", country: "UA", names: ["Yuzhnoukrainsk", "Южноукраинск", "Южноукраїнськ"] },
    { name: "Myrhorod", country: "UA", names: ["Myrhorod", "Mirgorod", "Миргород", "Миргород"] },
    { name: "Romny", country: "UA", names: ["Romny", "Ромны", "Ромни"] },
    { name: "Pokrov", country: "UA", names: ["Pokrov", "Ordzhonikidze", "Покров", "Покров"] },
    { name: "Volodymyr", country: "UA", names: ["Volodymyr", "Vladimir-Volynsky", "Владимир", "Володимир"] },
    { name: "Dzhankoi", country: "UA", names: ["Dzhankoi", "Dzhankoy", "Джанкой", "Джанкой"] },
    { name: "Vasylkiv", country: "UA", names: ["Vasylkiv", "Vasilkov", "Васильков", "Васильків"] },
    { name: "Dubno", country: "UA", names: ["Dubno", "Дубно", "Дубно"] },
    { name: "Bucha", country: "UA", names: ["Bucha", "Буча", "Буча"] },
    { name: "Netishyn", country: "UA", names: ["Netishyn", "Neteshin", "Нетешин", "Нетішин"] },
    { name: "Pervomaisk", country: "UA", names: ["Pervomaisk", "Первомайск", "Первомайськ"] },
    { name: "Kakhovka", country: "UA", names: ["Kakhovka", "Каховка", "Каховка"] },
    { name: "Boyarka", country: "UA", names: ["Boyarka", "Боярка", "Боярка"] },
    { name: "Slavuta", country: "UA", names: ["Slavuta", "Славута", "Славута"] },
    { name: "Sambir", country: "UA", names: ["Sambir", "Sambor", "Самбор", "Самбір"] },
    { name: "Voznesensk", country: "UA", names: ["Voznesensk", "Вознесенск", "Вознесенськ"] },
    { name: "Yasynuvata", country: "UA", names: ["Yasynuvata", "Yasinovataya", "Ясиноватая", "Ясинувата"] },
    { name: "Zhmerynka", country: "UA", names: ["Zhmerynka", "Zhmerinka", "Жмеринка", "Жмеринка"] },
    { name: "Boryslav", country: "UA", names: ["Boryslav", "Borislav", "Борислав", "Борислав"] },
    { name: "Obukhiv", country: "UA", names: ["Obukhiv", "Obukhov", "Обухов", "Обухів"] },
    { name: "Tokmak", country: "UA", names: ["Tokmak", "Токмак", "Токмак"] },
    { name: "Chuhuiv", country: "UA", names: ["Chuhuiv", "Chuguev", "Чугуев", "Чугуїв"] },
    { name: "Mohyliv-Podilskyi", country: "UA", names: ["Mohyliv-Podilskyi", "Mogilev-Podolsky", "Могилев-Подольский", "Могилів-Подільський"] },
    { name: "Yuzhne", country: "UA", names: ["Yuzhne", "Yuzhny", "Южное", "Южне"] },
    { name: "Kostopil", country: "UA", names: ["Kostopil", "Kostopol", "Костополь", "Костопіль"] },
    { name: "Synelnykove", country: "UA", names: ["Synelnykove", "Sinelnikovo", "Синельниково", "Синельникове"] },
    { name: "Alushta", country: "UA", names: ["Alushta", "Алушта", "Алушта"] },
    { name: "Novoyavorivsk", country: "UA", names: ["Novoyavorivsk", "Новояворовск", "Новояворівськ"] },
    { name: "Kupiansk", country: "UA", names: ["Kupiansk", "Kupyansk", "Купянск", "Куп'янськ"] },
    { name: "Chortkiv", country: "UA", names: ["Chortkiv", "Chortkov", "Чортков", "Чортків"] },
    { name: "Balakliia", country: "UA", names: ["Balakliia", "Balakleya", "Балаклея", "Балаклія"] },
    { name: "Truskavets", country: "UA", names: ["Truskavets", "Трускавец", "Трускавець"] },
    { name: "Khust", country: "UA", names: ["Khust", "Хуст", "Хуст"] },
    { name: "Pershotravensk", country: "UA", names: ["Pershotravensk", "Першотравенск", "Першотравенськ"] },
    { name: "Novyi Rozdil", country: "UA", names: ["Novyi Rozdil", "Novy Rozdol", "Новый Роздол", "Новий Розділ"] },
    { name: "Ternivka", country: "UA", names: ["Ternivka", "Ternovka", "Терновка", "Тернівка"] },
    { name: "Sarny", country: "UA", names: ["Sarny", "Сарны", "Сарни"] },
    { name: "Zolotonosha", country: "UA", names: ["Zolotonosha", "Золотоноша", "Золотоноша"] },
    { name: "Khmilnyk", country: "UA", names: ["Khmilnyk", "Khmelnik", "Хмельник", "Хмільник"] },
    { name: "Hadiach", country: "UA", names: ["Hadiach", "Gadyach", "Гадяч", "Гадяч"] },
    { name: "Vyshhorod", country: "UA", names: ["Vyshhorod", "Vyshgorod", "Вышгород", "Вишгород"] },
    { name: "Pereiaslav", country: "UA", names: ["Pereiaslav", "Pereyaslav-Khmelnitsky", "Переяслав", "Переяслав"] },
    { name: "Malyn", country: "UA", names: ["Malyn", "Malin", "Малин", "Малин"] },
    { name: "Yagotyn", country: "UA", names: ["Yagotyn", "Yagotin", "Яготин", "Яготин"] },
    { name: "Fativ", country: "UA", names: ["Fativ", "Fastov", "Фастов", "Фастів"] }
];

export const searchCities = (query) => {
    if (!query || query.length < 2) return [];
    
    const normalizedQuery = normalize(query);
    
    return citiesData.filter(city => {
        return city.names.some(name => normalize(name).includes(normalizedQuery));
    });
};

export const getAllCities = () => citiesData;
