
// Helper to normalize strings for search (remove diacritics, lowercase)
const normalize = (str) => {
    if (!str) return "";
    return str.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase();
};

const citiesData = [
    // --- POLAND (PL) ---
    { name: "Warszawa", country: "PL", names: ["Warszawa", "Warsaw", "Варшава", "Варшава"] },
    { name: "Kraków", country: "PL", names: ["Kraków", "Cracow", "Краков", "Краків"] },
    { name: "Łódź", country: "PL", names: ["Łódź", "Lodz", "Лодзь", "Лодзь"] },
    { name: "Wrocław", country: "PL", names: ["Wrocław", "Wroclaw", "Вроцлав", "Вроцлав"] },
    { name: "Poznań", country: "PL", names: ["Poznań", "Poznan", "Познань", "Познань"] },
    { name: "Gdańsk", country: "PL", names: ["Gdańsk", "Gdansk", "Гданьск", "Гданськ"] },
    { name: "Szczecin", country: "PL", names: ["Szczecin", "Щецин", "Щецин"] },
    { name: "Bydgoszcz", country: "PL", names: ["Bydgoszcz", "Быдгощ", "Бидгощ"] },
    { name: "Lublin", country: "PL", names: ["Lublin", "Люблин", "Люблін"] },
    { name: "Białystok", country: "PL", names: ["Białystok", "Bialystok", "Белосток", "Білосток"] },
    { name: "Katowice", country: "PL", names: ["Katowice", "Катовице", "Катовіце"] },
    { name: "Gdynia", country: "PL", names: ["Gdynia", "Гдыня", "Гдиня"] },
    { name: "Częstochowa", country: "PL", names: ["Częstochowa", "Czestochowa", "Ченстохова", "Ченстохова"] },
    { name: "Radom", country: "PL", names: ["Radom", "Радом", "Радом"] },
    { name: "Rzeszów", country: "PL", names: ["Rzeszów", "Rzeszow", "Жешув", "Ряшів"] },
    { name: "Toruń", country: "PL", names: ["Toruń", "Torun", "Торунь", "Торунь"] },
    { name: "Kielce", country: "PL", names: ["Kielce", "Кельце", "Кельці"] },
    { name: "Gliwice", country: "PL", names: ["Gliwice", "Гливице", "Глівіце"] },
    { name: "Olsztyn", country: "PL", names: ["Olsztyn", "Ольштын", "Ольштин"] },
    { name: "Zabrze", country: "PL", names: ["Zabrze", "Забже", "Забже"] },
    { name: "Bielsko-Biała", country: "PL", names: ["Bielsko-Biała", "Bielsko-Biala", "Бельско-Бяла", "Бєльсько-Бяла"] },
    { name: "Bytom", country: "PL", names: ["Bytom", "Бытом", "Битом"] },
    { name: "Zielona Góra", country: "PL", names: ["Zielona Góra", "Zielona Gora", "Зелёна-Гура", "Зелена Гура"] },
    { name: "Rybnik", country: "PL", names: ["Rybnik", "Рыбник", "Рибник"] },
    { name: "Ruda Śląska", country: "PL", names: ["Ruda Śląska", "Ruda Slaska", "Руда-Слёнска", "Руда-Шльонська"] },
    { name: "Opole", country: "PL", names: ["Opole", "Ополе", "Ополе"] },
    { name: "Tychy", country: "PL", names: ["Tychy", "Тыхы", "Тихи"] },
    { name: "Gorzów Wielkopolski", country: "PL", names: ["Gorzów Wielkopolski", "Gorzow Wielkopolski", "Гожув-Велькопольски", "Гожув-Велькопольський"] },
    { name: "Dąbrowa Górnicza", country: "PL", names: ["Dąbrowa Górnicza", "Dabrowa Gornicza", "Домброва-Гурнича", "Домброва-Гурнича"] },
    { name: "Płock", country: "PL", names: ["Płock", "Plock", "Плоцк", "Плоцьк"] },
    { name: "Elbląg", country: "PL", names: ["Elbląg", "Elblag", "Эльблонг", "Ельблонг"] },
    { name: "Wałbrzych", country: "PL", names: ["Wałbrzych", "Walbrzych", "Валбжих", "Валбжих"] },
    { name: "Włocławek", country: "PL", names: ["Włocławek", "Wloclawek", "Влоцлавек", "Влоцлавек"] },
    { name: "Tarnów", country: "PL", names: ["Tarnów", "Tarnow", "Тарнув", "Тарнів"] },
    { name: "Chorzów", country: "PL", names: ["Chorzów", "Chorzow", "Хожув", "Хожув"] },
    { name: "Koszalin", country: "PL", names: ["Koszalin", "Кошалин", "Кошалін"] },
    { name: "Kalisz", country: "PL", names: ["Kalisz", "Калиш", "Каліш"] },
    { name: "Legnica", country: "PL", names: ["Legnica", "Легница", "Легниця"] },
    { name: "Grudziądz", country: "PL", names: ["Grudziądz", "Grudziadz", "Грудзёндз", "Грудзьондз"] },
    { name: "Jaworzno", country: "PL", names: ["Jaworzno", "Явожно", "Явожно"] },
    { name: "Słupsk", country: "PL", names: ["Słupsk", "Slupsk", "Слупск", "Слупськ"] },
    { name: "Jastrzębie-Zdrój", country: "PL", names: ["Jastrzębie-Zdrój", "Jastrzebie-Zdroj", "Ястшембе-Здруй", "Ястшембе-Здруй"] },
    { name: "Nowy Sącz", country: "PL", names: ["Nowy Sącz", "Nowy Sacz", "Новы-Сонч", "Новий Сонч"] },
    { name: "Jelenia Góra", country: "PL", names: ["Jelenia Góra", "Jelenia Gora", "Еленя-Гура", "Єленя-Гура"] },
    { name: "Siedlce", country: "PL", names: ["Siedlce", "Седльце", "Седльце"] },
    { name: "Mysłowice", country: "PL", names: ["Mysłowice", "Myslowice", "Мысловице", "Мисловіце"] },
    { name: "Konin", country: "PL", names: ["Konin", "Конин", "Конін"] },
    { name: "Piła", country: "PL", names: ["Piła", "Pila", "Пила", "Піла"] },
    { name: "Piotrków Trybunalski", country: "PL", names: ["Piotrków Trybunalski", "Piotrkow Trybunalski", "Пётркув-Трыбунальски", "Пйотркув-Трибунальський"] },
    { name: "Inowrocław", country: "PL", names: ["Inowrocław", "Inowroclaw", "Иновроцлав", "Іновроцлав"] },
    { name: "Lubin", country: "PL", names: ["Lubin", "Любин", "Любін"] },
    { name: "Ostrów Wielkopolski", country: "PL", names: ["Ostrów Wielkopolski", "Ostrow Wielkopolski", "Острув-Велькопольски", "Острув-Велькопольський"] },
    { name: "Suwałki", country: "PL", names: ["Suwałki", "Suwalki", "Сувалки", "Сувалки"] },
    { name: "Stargard", country: "PL", names: ["Stargard", "Старгард", "Старгард"] },
    { name: "Gniezno", country: "PL", names: ["Gniezno", "Гнезно", "Гнєзно"] },
    { name: "Ostrowiec Świętokrzyski", country: "PL", names: ["Ostrowiec Świętokrzyski", "Ostrowiec Swietokrzyski", "Островец-Свентокшиски", "Островець-Свентокшиський"] },
    { name: "Siemianowice Śląskie", country: "PL", names: ["Siemianowice Śląskie", "Siemianowice Slaskie", "Семяновице-Слёнске", "Семяновіце-Шльонське"] },
    { name: "Głogów", country: "PL", names: ["Głogów", "Glogow", "Глогув", "Глогув"] },
    { name: "Pabianice", country: "PL", names: ["Pabianice", "Пабьянице", "Паб'яніце"] },
    { name: "Leszno", country: "PL", names: ["Leszno", "Лешно", "Лешно"] },
    { name: "Żory", country: "PL", names: ["Żory", "Zory", "Жоры", "Жори"] },
    { name: "Zamość", country: "PL", names: ["Zamość", "Zamosc", "Замосць", "Замостя"] },
    { name: "Pruszków", country: "PL", names: ["Pruszków", "Pruszkow", "Прушков", "Прушкув"] },
    { name: "Łomża", country: "PL", names: ["Łomża", "Lomza", "Ломжа", "Ломжа"] },
    { name: "Ełk", country: "PL", names: ["Ełk", "Elk", "Элк", "Елк"] },
    { name: "Tarnowskie Góry", country: "PL", names: ["Tarnowskie Góry", "Tarnowskie Gory", "Тарновске-Гуры", "Тарновські Гури"] },
    { name: "Tomaszów Mazowiecki", country: "PL", names: ["Tomaszów Mazowiecki", "Tomaszow Mazowiecki", "Томашув-Мазовецки", "Томашув-Мазовецький"] },
    { name: "Chełm", country: "PL", names: ["Chełm", "Chelm", "Хелм", "Холм"] },
    { name: "Mielec", country: "PL", names: ["Mielec", "Мелец", "Мелець"] },
    { name: "Kędzierzyn-Koźle", country: "PL", names: ["Kędzierzyn-Koźle", "Kedzierzyn-Kozle", "Кендзежин-Козле", "Кендзежин-Козле"] },
    { name: "Przemyśl", country: "PL", names: ["Przemyśl", "Przemysl", "Пшемысль", "Перемишль"] },
    { name: "Stalowa Wola", country: "PL", names: ["Stalowa Wola", "Сталёва-Воля", "Стальова Воля"] },
    { name: "Tczew", country: "PL", names: ["Tczew", "Тчев", "Тчев"] },
    { name: "Biała Podlaska", country: "PL", names: ["Biała Podlaska", "Biala Podlaska", "Бяла-Подляска", "Бяла-Подляська"] },
    { name: "Bełchatów", country: "PL", names: ["Bełchatów", "Belchatow", "Белхатув", "Белхатув"] },
    { name: "Świdnica", country: "PL", names: ["Świdnica", "Swidnica", "Свидница", "Свідниця"] },
    { name: "Będzin", country: "PL", names: ["Będzin", "Bedzin", "Бендзин", "Бендзин"] },
    { name: "Zgierz", country: "PL", names: ["Zgierz", "Згеж", "Згеж"] },
    { name: "Piekary Śląskie", country: "PL", names: ["Piekary Śląskie", "Piekary Slaskie", "Пекары-Слёнске", "Пекари-Шльонські"] },
    { name: "Racibórz", country: "PL", names: ["Racibórz", "Raciborz", "Рацибуж", "Рацибуж"] },
    { name: "Legionowo", country: "PL", names: ["Legionowo", "Легионово", "Легіоново"] },
    { name: "Ostrołęka", country: "PL", names: ["Ostrołęka", "Ostroleka", "Остроленка", "Остроленка"] },
    { name: "Świętochłowice", country: "PL", names: ["Świętochłowice", "Swietochlowice", "Свентохловице", "Свентохловиці"] },
    { name: "Wejherowo", country: "PL", names: ["Wejherowo", "Вейхерово", "Вейхерово"] },
    { name: "Zawiercie", country: "PL", names: ["Zawiercie", "Заверце", "Заверці"] },
    { name: "Skierniewice", country: "PL", names: ["Skierniewice", "Скерневице", "Скерневиці"] },
    { name: "Starachowice", country: "PL", names: ["Starachowice", "Стараховице", "Стараховіце"] },
    { name: "Wodzisław Śląski", country: "PL", names: ["Wodzisław Śląski", "Wodzislaw Slaski", "Водзислав-Слёнски", "Водзіслав-Шльонський"] },
    { name: "Starogard Gdański", country: "PL", names: ["Starogard Gdański", "Starogard Gdanski", "Старогард-Гданьски", "Старогард-Гданський"] },
    { name: "Puławy", country: "PL", names: ["Puławy", "Pulawy", "Пулавы", "Пулави"] },
    { name: "Tarnobrzeg", country: "PL", names: ["Tarnobrzeg", "Тарнобжег", "Тарнобжег"] },
    { name: "Kołobrzeg", country: "PL", names: ["Kołobrzeg", "Kolobrzeg", "Колобжег", "Колобжег"] },
    { name: "Krosno", country: "PL", names: ["Krosno", "Кросно", "Кросно"] },
    { name: "Radomsko", country: "PL", names: ["Radomsko", "Радомско", "Радомсько"] },
    { name: "Otwock", country: "PL", names: ["Otwock", "Отвоцк", "Отвоцьк"] },
    { name: "Skarżysko-Kamienna", country: "PL", names: ["Skarżysko-Kamienna", "Skarzysko-Kamienna", "Скаржиско-Каменна", "Скаржисько-Каменна"] },
    { name: "Ciechanów", country: "PL", names: ["Ciechanów", "Ciechanow", "Цеханув", "Цеханув"] },
    { name: "Kutno", country: "PL", names: ["Kutno", "Кутно", "Кутно"] },
    { name: "Sieradz", country: "PL", names: ["Sieradz", "Серадз", "Серадз"] },
    { name: "Zduńska Wola", country: "PL", names: ["Zduńska Wola", "Zdunska Wola", "Здуньска-Воля", "Здунська-Воля"] },
    { name: "Świnoujście", country: "PL", names: ["Świnoujście", "Swinoujscie", "Свиноуйсьце", "Свіноуйсьце"] },
    { name: "Żyrardów", country: "PL", names: ["Żyrardów", "Zyrardow", "Жирардув", "Жирардув"] },
    { name: "Bolesławiec", country: "PL", names: ["Bolesławiec", "Boleslawiec", "Болеславец", "Болеславець"] },
    { name: "Nowa Sól", country: "PL", names: ["Nowa Sól", "Nowa Sol", "Нова-Суль", "Нова Суль"] },
    { name: "Knurów", country: "PL", names: ["Knurów", "Knurow", "Кнурув", "Кнурув"] },
    { name: "Oświęcim", country: "PL", names: ["Oświęcim", "Oswiecim", "Освенцим", "Освенцим"] },
    { name: "Sopot", country: "PL", names: ["Sopot", "Сопот", "Сопот"] },
    { name: "Sanok", country: "PL", names: ["Sanok", "Санок", "Сянок"] },
    { name: "Rumia", country: "PL", names: ["Rumia", "Румя", "Румя"] },
    { name: "Jarosław", country: "PL", names: ["Jarosław", "Jaroslaw", "Ярослав", "Ярослав"] },
    { name: "Żywiec", country: "PL", names: ["Żywiec", "Zywiec", "Живец", "Живець"] },
    { name: "Szczecinek", country: "PL", names: ["Szczecinek", "Щецинек", "Щецинек"] },
    { name: "Chojnice", country: "PL", names: ["Chojnice", "Хойнице", "Хойніце"] },
    { name: "Malbork", country: "PL", names: ["Malbork", "Мальборк", "Мальборк"] },
    { name: "Kwidzyn", country: "PL", names: ["Kwidzyn", "Квидзын", "Квідзин"] },
    { name: "Kraśnik", country: "PL", names: ["Kraśnik", "Krasnik", "Красник", "Красник"] },
    { name: "Mława", country: "PL", names: ["Mława", "Mlawa", "Млава", "Млава"] },
    { name: "Września", country: "PL", names: ["Września", "Wrzesnia", "Вжесня", "Вжесня"] },
    { name: "Łuków", country: "PL", names: ["Łuków", "Lukow", "Лукув", "Луків"] },
    { name: "Wołomin", country: "PL", names: ["Wołomin", "Wolomin", "Воломин", "Воломін"] },
    { name: "Czeladź", country: "PL", names: ["Czeladź", "Czeladz", "Челядзь", "Челядзь"] },
    { name: "Lębork", country: "PL", names: ["Lębork", "Lebork", "Лемборк", "Лемборк"] },
    { name: "Cieszyn", country: "PL", names: ["Cieszyn", "Цешин", "Цешин"] },
    { name: "Piaseczno", country: "PL", names: ["Piaseczno", "Пясечно", "Пясечно"] },
    { name: "Zgorzelec", country: "PL", names: ["Zgorzelec", "Згожелец", "Згожелець"] },
    { name: "Zakopane", country: "PL", names: ["Zakopane", "Закопане", "Закопане"] },

    // --- BELARUS (BY) ---
    { name: "Минск", country: "BY", names: ["Minsk", "Mińsk", "Минск", "Мінськ"] },
    { name: "Гомель", country: "BY", names: ["Gomel", "Homel", "Гомель", "Гомель"] },
    { name: "Могилев", country: "BY", names: ["Mogilev", "Mahilyow", "Могилев", "Могильов"] },
    { name: "Витебск", country: "BY", names: ["Vitebsk", "Vitsyebsk", "Витебск", "Вітебськ"] },
    { name: "Гродно", country: "BY", names: ["Grodno", "Hrodna", "Гродно", "Гродно"] },
    { name: "Брест", country: "BY", names: ["Brest", "Брест", "Брест"] },
    { name: "Бобруйск", country: "BY", names: ["Bobruisk", "Babruysk", "Бобруйск", "Бобруйськ"] },
    { name: "Барановичи", country: "BY", names: ["Baranovichi", "Baranavichy", "Барановичи", "Барановичі"] },
    { name: "Борисов", country: "BY", names: ["Borisov", "Barysaw", "Борисов", "Борисов"] },
    { name: "Пинск", country: "BY", names: ["Pinsk", "Пинск", "Пінськ"] },
    { name: "Орша", country: "BY", names: ["Orsha", "Arsha", "Орша", "Орша"] },
    { name: "Мозырь", country: "BY", names: ["Mozyr", "Mazyr", "Мозырь", "Мозир"] },
    { name: "Солигорск", country: "BY", names: ["Soligorsk", "Salihorsk", "Солигорск", "Солігорськ"] },
    { name: "Лида", country: "BY", names: ["Lida", "Лида", "Ліда"] },
    { name: "Новополоцк", country: "BY", names: ["Novopolotsk", "Navapolatsk", "Новополоцк", "Новополоцьк"] },
    { name: "Молодечно", country: "BY", names: ["Molodechno", "Maladzyechna", "Молодечно", "Молодечно"] },
    { name: "Полоцк", country: "BY", names: ["Polotsk", "Polatsk", "Полоцк", "Полоцьк"] },
    { name: "Жлобин", country: "BY", names: ["Zhlobin", "Жлобин", "Жлобин"] },
    { name: "Светлогорск", country: "BY", names: ["Svetlogorsk", "Svietlahorsk", "Светлогорск", "Світлогорськ"] },
    { name: "Речица", country: "BY", names: ["Rechitsa", "Rechytsa", "Речица", "Річиця"] },
    { name: "Слуцк", country: "BY", names: ["Slutsk", "Слуцк", "Слуцьк"] },
    { name: "Жодино", country: "BY", names: ["Zhodino", "Zhodzina", "Жодино", "Жодіно"] },
    { name: "Слоним", country: "BY", names: ["Slonim", "Слоним", "Слонім"] },
    { name: "Кобрин", country: "BY", names: ["Kobrin", "Kobryn", "Кобрин", "Кобринь"] },
    { name: "Волковыск", country: "BY", names: ["Volkovysk", "Vawkavysk", "Волковыск", "Вовковиськ"] },
    { name: "Калинковичи", country: "BY", names: ["Kalinkovichi", "Kalinkavichy", "Калинковичи", "Калинковичі"] },
    { name: "Сморгонь", country: "BY", names: ["Smorgon", "Smarhon", "Сморгонь", "Сморгонь"] },
    { name: "Рогачев", country: "BY", names: ["Rogachev", "Rahachow", "Рогачев", "Рогачов"] },
    { name: "Осиповичи", country: "BY", names: ["Osipovichi", "Asipovichy", "Осиповичи", "Осиповичі"] },
    { name: "Горки", country: "BY", names: ["Gorki", "Horki", "Горки", "Гірки"] },
    { name: "Новогрудок", country: "BY", names: ["Novogrudok", "Navahrudak", "Новогрудок", "Новогрудок"] },
    { name: "Вилейка", country: "BY", names: ["Vilejka", "Vileyka", "Вилейка", "Вілейка"] },
    { name: "Береза", country: "BY", names: ["Berezha", "Byaroza", "Береза", "Береза"] },
    { name: "Кричев", country: "BY", names: ["Krichev", "Krychaw", "Кричев", "Кричев"] },
    { name: "Дзержинск", country: "BY", names: ["Dzerzhinsk", "Dzyarzhynsk", "Дзержинск", "Дзержинськ"] },
    { name: "Ивацевичи", country: "BY", names: ["Ivatsevichi", "Ivatsevichy", "Ивацевичи", "Івацевичі"] },
    { name: "Лунинец", country: "BY", names: ["Luninets", "Лунинец", "Лунинець"] },
    { name: "Марьина Горка", country: "BY", names: ["Maryina Gorka", "Maryina Horka", "Марьина Горка", "Мар'їна Гірка"] },
    { name: "Поставы", country: "BY", names: ["Postavy", "Pastavy", "Поставы", "Постави"] },
    { name: "Пружаны", country: "BY", names: ["Pruzhany", "Пружаны", "Пружани"] },
    { name: "Глубокое", country: "BY", names: ["Glubokoe", "Hlybokaye", "Глубокое", "Глибоке"] },
    { name: "Добруш", country: "BY", names: ["Dobrush", "Добруш", "Добруш"] },
    { name: "Лепель", country: "BY", names: ["Lepel", "Лепель", "Лепель"] },
    { name: "Быхов", country: "BY", names: ["Bykhov", "Bykhaw", "Быхов", "Бихов"] },
    { name: "Иваново", country: "BY", names: ["Ivanovo", "Ivanava", "Иваново", "Іванове"] },
    { name: "Климовичи", country: "BY", names: ["Klimovichi", "Klimavichy", "Климовичи", "Климовичі"] },
    { name: "Шклов", country: "BY", names: ["Shklov", "Shklow", "Шклов", "Шклов"] },
    { name: "Столбцы", country: "BY", names: ["Stolbtsy", "Stowbtsy", "Столбцы", "Стовбці"] },
    { name: "Костюковичи", country: "BY", names: ["Kostyukovichi", "Kastsyukovichy", "Костюковичи", "Костюковичі"] },
    { name: "Житковичи", country: "BY", names: ["Zhitkovichi", "Zhytkavichy", "Житковичи", "Житковичі"] },
    { name: "Мосты", country: "BY", names: ["Mosty", "Masty", "Мосты", "Мости"] },
    { name: "Ошмяны", country: "BY", names: ["Oshmyany", "Ashmyany", "Ошмяны", "Ошмяни"] },
    { name: "Смолевичи", country: "BY", names: ["Smolevichi", "Smalyavichy", "Смолевичи", "Смолевичі"] },
    { name: "Щучин", country: "BY", names: ["Shchuchin", "Shchuchyn", "Щучин", "Щучин"] },
    { name: "Несвиж", country: "BY", names: ["Nesvizh", "Niasvizh", "Несвиж", "Несвіж"] },
    { name: "Заславль", country: "BY", names: ["Zaslavl", "Zaslawye", "Заславль", "Заславль"] },
    { name: "Фаниполь", country: "BY", names: ["Fanipol", "Fanipal", "Фаниполь", "Фаніполь"] },
    { name: "Дрогичин", country: "BY", names: ["Drogichin", "Drahichyn", "Дрогичин", "Дрогичин"] },
    { name: "Ганцевичи", country: "BY", names: ["Gantsevichi", "Hantsavichy", "Ганцевичи", "Ганцевичі"] },
    { name: "Жабинка", country: "BY", names: ["Zhabinka", "Жабинка", "Жабинка"] },
    { name: "Столин", country: "BY", names: ["Stolin", "Столин", "Столін"] },
    { name: "Микашевичи", country: "BY", names: ["Mikashevichi", "Mikashevichy", "Микашевичи", "Мікашевичі"] },
    { name: "Белоозёрск", country: "BY", names: ["Beloozersk", "Byaloazyorsk", "Белоозёрск", "Білоозерськ"] },
    { name: "Малорита", country: "BY", names: ["Malorita", "Malaryta", "Малорита", "Малорита"] },
    { name: "Ляховичи", country: "BY", names: ["Lyakhovichi", "Lyakhavichy", "Ляховичи", "Ляховичі"] },
    { name: "Скидель", country: "BY", names: ["Skidel", "Skidzyel", "Скидель", "Скідель"] },
    { name: "Березино", country: "BY", names: ["Berezino", "Berazino", "Березино", "Березине"] },
    { name: "Воложин", country: "BY", names: ["Volozhin", "Valozhyn", "Воложин", "Воложин"] },
    { name: "Петриков", country: "BY", names: ["Petrikov", "Petrykaw", "Петриков", "Петриков"] },
    { name: "Городок", country: "BY", names: ["Gorodok", "Haradok", "Городок", "Городок"] },
    { name: "Клецк", country: "BY", names: ["Kletsk", "Klyetsk", "Клецк", "Клецьк"] },
    { name: "Червень", country: "BY", names: ["Cherven", "Chervyen", "Червень", "Червень"] },
    { name: "Копыль", country: "BY", names: ["Kopyl", "Kapyl", "Копыль", "Копиль"] },
    { name: "Узда", country: "BY", names: ["Uzda", "Узда", "Узда"] },
    { name: "Крупки", country: "BY", names: ["Krupki", "Крупки", "Крупки"] },
    { name: "Толочин", country: "BY", names: ["Tolochin", "Talachyn", "Толочин", "Толочин"] },
    { name: "Браслав", country: "BY", names: ["Braslav", "Braslaw", "Браслав", "Браслав"] },
    { name: "Хойники", country: "BY", names: ["Khoiniki", "Khoyniki", "Хойники", "Хойники"] },
    { name: "Чаусы", country: "BY", names: ["Chausy", "Chavusy", "Чаусы", "Чауси"] },
    { name: "Мстиславль", country: "BY", names: ["Mstislavl", "Mstsislaw", "Мстиславль", "Мстиславль"] },
    { name: "Логойск", country: "BY", names: ["Logoisk", "Lahoysk", "Логойск", "Логойськ"] },
    { name: "Любань", country: "BY", names: ["Lyuban", "Любань", "Любань"] },
    { name: "Мядель", country: "BY", names: ["Myadel", "Myadzyel", "Мядель", "Мядель"] },
    { name: "Сенно", country: "BY", names: ["Senno", "Syanno", "Сенно", "Сенно"] },
    { name: "Верхнедвинск", country: "BY", names: ["Verkhnedvinsk", "Verkhnyadzvinsk", "Верхнедвинск", "Верхньодвінськ"] },
    { name: "Дубровно", country: "BY", names: ["Dubrovno", "Dubrowna", "Дубровно", "Дубровно"] },
    { name: "Докшицы", country: "BY", names: ["Dokshitsy", "Dokshytsy", "Докшицы", "Докшиці"] },
    { name: "Миоры", country: "BY", names: ["Miory", "Miyory", "Миоры", "Міори"] },
    { name: "Шарковщина", country: "BY", names: ["Sharkovshchina", "Sharkawshchyna", "Шарковщина", "Шарківщина"] },
    { name: "Бешенковичи", country: "BY", names: ["Beshenkovichi", "Bishankovichy", "Бешенковичи", "Бешенковичі"] },
    { name: "Ушачи", country: "BY", names: ["Ushachi", "Ushachy", "Ушачи", "Ушачі"] },
    { name: "Ветка", country: "BY", names: ["Vetka", "Ветка", "Вєтка"] },
    { name: "Чечерск", country: "BY", names: ["Chechersk", "Chachersk", "Чечерск", "Чечерськ"] },
    { name: "Наровля", country: "BY", names: ["Narovlya", "Narowlya", "Наровля", "Наровля"] },
    { name: "Лельчицы", country: "BY", names: ["Lelchitsy", "Lyelchytsy", "Лельчицы", "Лельчиці"] },
    { name: "Ельск", country: "BY", names: ["Yelsk", "Yel'sk", "Ельск", "Єльськ"] },
    { name: "Белыничи", country: "BY", names: ["Belynichi", "Byalynichy", "Белыничи", "Бєлиничі"] },
    { name: "Круглое", country: "BY", names: ["Krugloe", "Kruhlaye", "Круглое", "Кругле"] },
    { name: "Кировск", country: "BY", names: ["Kirovsk", "Kirawsk", "Кировск", "Кіровськ"] },
    { name: "Старые Дороги", country: "BY", names: ["Starye Dorogi", "Staryya Darohi", "Старые Дороги", "Старі Дороги"] },

    // --- UKRAINE (UA) ---
    { name: "Київ", country: "UA", names: ["Kyiv", "Kiev", "Kijów", "Киев", "Київ"] },
    { name: "Харків", country: "UA", names: ["Kharkiv", "Kharkov", "Charków", "Харьков", "Харків"] },
    { name: "Одеса", country: "UA", names: ["Odesa", "Odessa", "Одесса", "Одеса"] },
    { name: "Дніпро", country: "UA", names: ["Dnipro", "Dnepr", "Dniepr", "Днепр", "Дніпро"] },
    { name: "Донецьк", country: "UA", names: ["Donetsk", "Донецк", "Донецьк"] },
    { name: "Запоріжжя", country: "UA", names: ["Zaporizhzhia", "Zaporozhye", "Запорожье", "Запоріжжя"] },
    { name: "Львів", country: "UA", names: ["Lviv", "Lvov", "Lwów", "Львов", "Львів"] },
    { name: "Кривий Ріг", country: "UA", names: ["Kryvyi Rih", "Krivoy Rog", "Кривой Рог", "Кривий Ріг"] },
    { name: "Миколаїв", country: "UA", names: ["Mykolaiv", "Nikolaev", "Николаев", "Миколаїв"] },
    { name: "Маріуполь", country: "UA", names: ["Mariupol", "Мариуполь", "Маріуполь"] },
    { name: "Луганськ", country: "UA", names: ["Luhansk", "Lugansk", "Луганск", "Луганськ"] },
    { name: "Вінниця", country: "UA", names: ["Vinnytsia", "Vinnitsa", "Винница", "Вінниця"] },
    { name: "Макіївка", country: "UA", names: ["Makiivka", "Makeevka", "Макеевка", "Макіївка"] },
    { name: "Севастополь", country: "UA", names: ["Sevastopol", "Севастополь", "Севастополь"] },
    { name: "Сімферополь", country: "UA", names: ["Simferopol", "Симферополь", "Сімферополь"] },
    { name: "Херсон", country: "UA", names: ["Kherson", "Херсон", "Херсон"] },
    { name: "Полтава", country: "UA", names: ["Poltava", "Полтава", "Полтава"] },
    { name: "Чернігів", country: "UA", names: ["Chernihiv", "Chernigov", "Чернигов", "Чернігів"] },
    { name: "Черкаси", country: "UA", names: ["Cherkasy", "Cherkassy", "Черкассы", "Черкаси"] },
    { name: "Хмельницький", country: "UA", names: ["Khmelnytskyi", "Khmelnitsky", "Хмельницкий", "Хмельницький"] },
    { name: "Житомир", country: "UA", names: ["Zhytomyr", "Zhitomir", "Житомир", "Житомир"] },
    { name: "Чернівці", country: "UA", names: ["Chernivtsi", "Chernovtsy", "Черновцы", "Чернівці"] },
    { name: "Суми", country: "UA", names: ["Sumy", "Сумы", "Суми"] },
    { name: "Рівне", country: "UA", names: ["Rivne", "Rovno", "Ровно", "Рівне"] },
    { name: "Івано-Франківськ", country: "UA", names: ["Ivano-Frankivsk", "Ивано-Франковск", "Івано-Франківськ"] },
    { name: "Кам'янське", country: "UA", names: ["Kamianske", "Dneprodzerzhinsk", "Каменское", "Кам'янське"] },
    { name: "Кропивницький", country: "UA", names: ["Kropyvnytskyi", "Kirovograd", "Кропивницкий", "Кропивницький"] },
    { name: "Тернопіль", country: "UA", names: ["Ternopil", "Ternopol", "Тернополь", "Тернопіль"] },
    { name: "Кременчук", country: "UA", names: ["Kremenchuk", "Kremenchug", "Кременчуг", "Кременчук"] },
    { name: "Луцьк", country: "UA", names: ["Lutsk", "Луцк", "Луцьк"] },
    { name: "Біла Церква", country: "UA", names: ["Bila Tserkva", "Belaya Tserkov", "Белая Церковь", "Біла Церква"] },
    { name: "Ужгород", country: "UA", names: ["Uzhhorod", "Uzhgorod", "Ужгород", "Ужгород"] },
    { name: "Краматорськ", country: "UA", names: ["Kramatorsk", "Краматорск", "Краматорськ"] },
    { name: "Мелітополь", country: "UA", names: ["Melitopol", "Мелитополь", "Мелітополь"] },
    { name: "Керч", country: "UA", names: ["Kerch", "Керчь", "Керч"] },
    { name: "Нікополь", country: "UA", names: ["Nikopol", "Никополь", "Нікополь"] },
    { name: "Слов'янськ", country: "UA", names: ["Sloviansk", "Slavyansk", "Славянск", "Слов'янськ"] },
    { name: "Бердянськ", country: "UA", names: ["Berdiansk", "Berdyansk", "Бердянск", "Бердянськ"] },
    { name: "Алчевськ", country: "UA", names: ["Alchevsk", "Алчевск", "Алчевськ"] },
    { name: "Павлоград", country: "UA", names: ["Pavlohrad", "Pavlograd", "Павлоград", "Павлоград"] },
    { name: "Сєвєродонецьк", country: "UA", names: ["Sievierodonetsk", "Severodonetsk", "Северодонецк", "Сєвєродонецьк"] },
    { name: "Євпаторія", country: "UA", names: ["Yevpatoria", "Евпатория", "Євпаторія"] },
    { name: "Лисичанськ", country: "UA", names: ["Lysychansk", "Lisichansk", "Лисичанск", "Лисичанськ"] },
    { name: "Кам'янець-Подільський", country: "UA", names: ["Kamianets-Podilskyi", "Kamenets-Podolsky", "Каменец-Подольский", "Кам'янець-Подільський"] },
    { name: "Бровари", country: "UA", names: ["Brovary", "Бровары", "Бровари"] },
    { name: "Конотоп", country: "UA", names: ["Konotop", "Конотоп", "Конотоп"] },
    { name: "Умань", country: "UA", names: ["Uman", "Умань", "Умань"] },
    { name: "Мукачево", country: "UA", names: ["Mukachevo", "Mukacheve", "Мукачево", "Мукачево"] },
    { name: "Олександрія", country: "UA", names: ["Oleksandriia", "Alexandria", "Александрия", "Олександрія"] },
    { name: "Хрустальний", country: "UA", names: ["Khrustalnyi", "Krasny Luch", "Красный Луч", "Хрустальний"] },
    { name: "Єнакієве", country: "UA", names: ["Yenakiieve", "Yenakievo", "Енакиево", "Єнакієве"] },
    { name: "Дрогобич", country: "UA", names: ["Drohobych", "Drogobych", "Дрогобыч", "Дрогобич"] },
    { name: "Бердичів", country: "UA", names: ["Berdychiv", "Berdichev", "Бердичев", "Бердичів"] },
    { name: "Шостка", country: "UA", names: ["Shostka", "Шостка", "Шостка"] },
    { name: "Бахмут", country: "UA", names: ["Bakhmut", "Artemovsk", "Бахмут", "Бахмут"] },
    { name: "Ізмаїл", country: "UA", names: ["Izmail", "Измаил", "Ізмаїл"] },
    { name: "Новомосковськ", country: "UA", names: ["Novomoskovsk", "Новомосковск", "Новомосковськ"] },
    { name: "Костянтинівка", country: "UA", names: ["Kostiantynivka", "Konstantinovka", "Константиновка", "Костянтинівка"] },
    { name: "Ковель", country: "UA", names: ["Kovel", "Ковель", "Ковель"] },
    { name: "Феодосія", country: "UA", names: ["Feodosia", "Феодосия", "Феодосія"] },
    { name: "Ніжин", country: "UA", names: ["Nizhyn", "Nezhin", "Нежин", "Ніжин"] },
    { name: "Сміла", country: "UA", names: ["Smila", "Smela", "Смела", "Сміла"] },
    { name: "Калуш", country: "UA", names: ["Kalush", "Калуш", "Калуш"] },
    { name: "Червоноград", country: "UA", names: ["Chervonohrad", "Chervonograd", "Червоноград", "Червоноград"] },
    { name: "Бориспіль", country: "UA", names: ["Boryspil", "Borispol", "Борисполь", "Бориспіль"] },
    { name: "Первомайськ", country: "UA", names: ["Pervomaisk", "Первомайск", "Первомайськ"] },
    { name: "Ірпінь", country: "UA", names: ["Irpin", "Ирпень", "Ірпінь"] },
    { name: "Коростень", country: "UA", names: ["Korosten", "Коростень", "Коростень"] },
    { name: "Покровськ", country: "UA", names: ["Pokrovsk", "Krasnoarmeysk", "Покровск", "Покровськ"] },
    { name: "Коломия", country: "UA", names: ["Kolomyia", "Kolomyya", "Коломыя", "Коломия"] },
    { name: "Стрий", country: "UA", names: ["Stryi", "Stryy", "Стрый", "Стрий"] },
    { name: "Чорноморськ", country: "UA", names: ["Chornomorsk", "Illichivsk", "Черноморск", "Чорноморськ"] },
    { name: "Харцизьк", country: "UA", names: ["Khartsyzk", "Харцызск", "Харцизьк"] },
    { name: "Рубіжне", country: "UA", names: ["Rubizhne", "Rubezhnoe", "Рубежное", "Рубіжне"] },
    { name: "Новоград-Волинський", country: "UA", names: ["Novohrad-Volynskyi", "Novograd-Volynsky", "Новоград-Волынский", "Новоград-Волинський"] },
    { name: "Дружківка", country: "UA", names: ["Druzhkivka", "Druzhkovka", "Дружковка", "Дружківка"] },
    { name: "Лозова", country: "UA", names: ["Lozova", "Lozovaya", "Лозовая", "Лозова"] },
    { name: "Чистякове", country: "UA", names: ["Chystiakove", "Torez", "Чистяково", "Чистякове"] },
    { name: "Енергодар", country: "UA", names: ["Enerhodar", "Energodar", "Энергодар", "Енергодар"] },
    { name: "Прилуки", country: "UA", names: ["Pryluky", "Priluki", "Прилуки", "Прилуки"] },
    { name: "Антрацит", country: "UA", names: ["Antratsyt", "Antratsit", "Антрацит", "Антрацит"] },
    { name: "Нововолинськ", country: "UA", names: ["Novovolynsk", "Нововолынск", "Нововолинськ"] },
    { name: "Горішні Плавні", country: "UA", names: ["Horishni Plavni", "Komsomolsk", "Горишние Плавни", "Горішні Плавні"] },
    { name: "Шахтарськ", country: "UA", names: ["Shakhtarsk", "Shakhtersk", "Шахтерск", "Шахтарськ"] },
    { name: "Білгород-Дністровський", country: "UA", names: ["Bilhorod-Dnistrovskyi", "Belgorod-Dnestrovsky", "Белгород-Днестровский", "Білгород-Дністровський"] },
    { name: "Охтирка", country: "UA", names: ["Okhtyrka", "Akhtyrka", "Ахтырка", "Охтирка"] },
    { name: "Мирноград", country: "UA", names: ["Myrnohrad", "Dimitrov", "Мирноград", "Мирноград"] },
    { name: "Сніжне", country: "UA", names: ["Snizhne", "Snezhnoe", "Снежное", "Сніжне"] },
    { name: "Ізюм", country: "UA", names: ["Izium", "Izyum", "Изюм", "Ізюм"] },
    { name: "Марганець", country: "UA", names: ["Marhanets", "Marganets", "Марганец", "Марганець"] },
    { name: "Ровеньки", country: "UA", names: ["Rovenky", "Rovenki", "Ровеньки", "Ровеньки"] },
    { name: "Нова Каховка", country: "UA", names: ["Nova Kakhovka", "Новая Каховка", "Нова Каховка"] },
    { name: "Брянка", country: "UA", names: ["Brianka", "Bryanka", "Брянка", "Брянка"] },
    { name: "Фастів", country: "UA", names: ["Fastiv", "Fastov", "Фастов", "Фастів"] },
    { name: "Лубни", country: "UA", names: ["Lubny", "Лубны", "Лубни"] },
    { name: "Світловодськ", country: "UA", names: ["Svitlovodsk", "Svetlovodsk", "Светловодск", "Світловодськ"] },
    { name: "Жовті Води", country: "UA", names: ["Zhovti Vody", "Zheltye Vody", "Желтые Воды", "Жовті Води"] },
    { name: "Сорокине", country: "UA", names: ["Krasnodon", "Sorokyne", "Краснодон", "Сорокине"] },
    { name: "Вишневе", country: "UA", names: ["Vyshneve", "Vishnevoe", "Вишневое", "Вишневе"] },
    { name: "Вараш", country: "UA", names: ["Varash", "Kuznetsovsk", "Вараш", "Вараш"] },
    { name: "Шепетівка", country: "UA", names: ["Shepetivka", "Shepetovka", "Шепетовка", "Шепетівка"] },
    { name: "Подільськ", country: "UA", names: ["Podilsk", "Kotovsk", "Подольск", "Подільськ"] },
    { name: "Южноукраїнськ", country: "UA", names: ["Yuzhnoukrainsk", "Южноукраинск", "Южноукраїнськ"] },
    { name: "Миргород", country: "UA", names: ["Myrhorod", "Mirgorod", "Миргород", "Миргород"] },
    { name: "Ромни", country: "UA", names: ["Romny", "Ромны", "Ромни"] },
    { name: "Покров", country: "UA", names: ["Pokrov", "Ordzhonikidze", "Покров", "Покров"] },
    { name: "Володимир", country: "UA", names: ["Volodymyr", "Vladimir-Volynsky", "Владимир", "Володимир"] },
    { name: "Джанкой", country: "UA", names: ["Dzhankoi", "Dzhankoy", "Джанкой", "Джанкой"] },
    { name: "Васильків", country: "UA", names: ["Vasylkiv", "Vasilkov", "Васильков", "Васильків"] },
    { name: "Дубно", country: "UA", names: ["Dubno", "Дубно", "Дубно"] },
    { name: "Буча", country: "UA", names: ["Bucha", "Буча", "Буча"] },
    { name: "Нетішин", country: "UA", names: ["Netishyn", "Neteshin", "Нетешин", "Нетішин"] },
    { name: "Первомайськ", country: "UA", names: ["Pervomaisk", "Первомайск", "Первомайськ"] },
    { name: "Каховка", country: "UA", names: ["Kakhovka", "Каховка", "Каховка"] },
    { name: "Боярка", country: "UA", names: ["Boyarka", "Боярка", "Боярка"] },
    { name: "Славута", country: "UA", names: ["Slavuta", "Славута", "Славута"] },
    { name: "Самбір", country: "UA", names: ["Sambir", "Sambor", "Самбор", "Самбір"] },
    { name: "Вознесенськ", country: "UA", names: ["Voznesensk", "Вознесенск", "Вознесенськ"] },
    { name: "Ясинувата", country: "UA", names: ["Yasynuvata", "Yasinovataya", "Ясиноватая", "Ясинувата"] },
    { name: "Жмеринка", country: "UA", names: ["Zhmerynka", "Zhmerinka", "Жмеринка", "Жмеринка"] },
    { name: "Борислав", country: "UA", names: ["Boryslav", "Borislav", "Борислав", "Борислав"] },
    { name: "Обухів", country: "UA", names: ["Obukhiv", "Obukhov", "Обухов", "Обухів"] },
    { name: "Токмак", country: "UA", names: ["Tokmak", "Токмак", "Токмак"] },
    { name: "Чугуїв", country: "UA", names: ["Chuhuiv", "Chuguev", "Чугуев", "Чугуїв"] },
    { name: "Могилів-Подільський", country: "UA", names: ["Mohyliv-Podilskyi", "Mogilev-Podolsky", "Могилев-Подольский", "Могилів-Подільський"] },
    { name: "Южне", country: "UA", names: ["Yuzhne", "Yuzhny", "Южное", "Южне"] },
    { name: "Костопіль", country: "UA", names: ["Kostopil", "Kostopol", "Костополь", "Костопіль"] },
    { name: "Синельникове", country: "UA", names: ["Synelnykove", "Sinelnikovo", "Синельниково", "Синельникове"] },
    { name: "Алушта", country: "UA", names: ["Alushta", "Алушта", "Алушта"] },
    { name: "Новояворівськ", country: "UA", names: ["Novoyavorivsk", "Новояворовск", "Новояворівськ"] },
    { name: "Куп'янськ", country: "UA", names: ["Kupiansk", "Kupyansk", "Купянск", "Куп'янськ"] },
    { name: "Чортків", country: "UA", names: ["Chortkiv", "Chortkov", "Чортков", "Чортків"] },
    { name: "Балаклія", country: "UA", names: ["Balakliia", "Balakleya", "Балаклея", "Балаклія"] },
    { name: "Трускавець", country: "UA", names: ["Truskavets", "Трускавец", "Трускавець"] },
    { name: "Хуст", country: "UA", names: ["Khust", "Хуст", "Хуст"] },
    { name: "Першотравенськ", country: "UA", names: ["Pershotravensk", "Першотравенск", "Першотравенськ"] },
    { name: "Новий Розділ", country: "UA", names: ["Novyi Rozdil", "Novy Rozdol", "Новый Роздол", "Новий Розділ"] },
    { name: "Тернівка", country: "UA", names: ["Ternivka", "Ternovka", "Терновка", "Тернівка"] },
    { name: "Сарни", country: "UA", names: ["Sarny", "Сарны", "Сарни"] },
    { name: "Золотоноша", country: "UA", names: ["Zolotonosha", "Золотоноша", "Золотоноша"] },
    { name: "Хмільник", country: "UA", names: ["Khmilnyk", "Khmelnik", "Хмельник", "Хмільник"] },
    { name: "Гадяч", country: "UA", names: ["Hadiach", "Gadyach", "Гадяч", "Гадяч"] },
    { name: "Вишгород", country: "UA", names: ["Vyshhorod", "Vyshgorod", "Вышгород", "Вишгород"] },
    { name: "Переяслав", country: "UA", names: ["Pereiaslav", "Pereyaslav-Khmelnitsky", "Переяслав", "Переяслав"] },
    { name: "Малин", country: "UA", names: ["Malyn", "Malin", "Малин", "Малин"] },
    { name: "Яготин", country: "UA", names: ["Yagotyn", "Yagotin", "Яготин", "Яготин"] },
    { name: "Фастів", country: "UA", names: ["Fativ", "Fastov", "Фастов", "Фастів"] }
];

export const searchCities = (query) => {
    if (!query || query.length < 2) return [];
    
    const normalizedQuery = normalize(query);
    
    return citiesData.filter(city => {
        return city.names.some(name => normalize(name).includes(normalizedQuery));
    });
};

export const getAllCities = () => citiesData;
